### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.isClosed()' on a null object reference

### ISSUE THREAD

**Issue by bviebahn** [vonovak/react-native-add-calendar-event#161]
I'm seeing this error in Crashlytics, but haven't been able to reproduce it. So far it only happened once, but it might still be worth fixing.
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.isClosed()' on a null object reference
       at com.vonovak.AddCalendarEventModule.onLoadFinished(AddCalendarEventModule.java:196)
       at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:497)
       at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:465)
       at android.content.Loader.deliverResult(Loader.java:157)
       at android.content.CursorLoader.deliverResult(CursorLoader.java:116)
       at android.content.CursorLoader.deliverResult(CursorLoader.java:46)
       at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:274)
       at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:97)
       at android.os.AsyncTask.finish(AsyncTask.java:771)
       at android.os.AsyncTask.access$900(AsyncTask.java:199)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7701)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

Device: Nokia 7.2
Android Version: 11

**Comment by m00gl3** [comment]
Also getting this on Crashlytics (and also for me a single Crash event)

Using react-native-add-calendar-event 4.2.2
react-native 0.72.3

**Comment by talhatsk** [comment]
+1
